version: '3.9'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  interpreted:
    build: ../interpreted
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.20.2
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      # - ./static:/var/html/static/ в случае раздачи статического контента
      # - ./media:/var/html/media/
    depends_on:
      - interpreted