# Generated by Django 3.1.4 on 2020-12-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storechain',
            old_name='store',
            new_name='stores',
        ),
    ]
